[tool.poetry]
name = "ventoy-macos"
version = "0.1.0"
description = "Install Ventoy on a USB drive from macOS."
authors = ["Alissa Huskey <alissa.huskey@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.scripts]
ventoy-macos = "ventoy_macos.cli:main"

[tool.poetry.dependencies]
python = "3.11"
attr = { git = "https://github.com/alissa-huskey/attr.git" }
rich = "^15.0.0"
requests = "^2.34.2"

[tool.poetry.group.dev.dependencies]
isort = "^8.0.1"
pynvim = "*"
pytest = "*"
pdbpp = "*"
ipython = "*"
pylama = "*"
pylint = "*"
black = "*"
pycodestyle = "*"
flake8 = "*"
flake8-black = "*"
flake8-docstrings = "*"
flake8-isort = "*"
pyfakefs = "^6.2.0"

[tool.pytest.ini_options]
addopts = "-xv"
testpaths = "tests"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
